---

version: '3.3'
services:

  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ./selenoidConfig:/etc/selenoid
      - "/var/run/docker.sock:/var/run/docker.sock"

  tests:
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/home/gradle/build
    command: gradle web -Dselenide.remote=http://selenoid:4444/wd/hub
    depends_on:
      - selenoid
    links:
      - selenoid
